# Generated by Django 2.2.7 on 2019-12-10 05:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20191210_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
