# Generated by Django 2.2.7 on 2019-12-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_comment_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.Post'),
        ),
    ]
