# Generated by Django 2.2.7 on 2019-12-12 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20191211_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_comments', to='forum.Post'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
