# Generated by Django 2.2.7 on 2019-12-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20191221_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
