# Generated by Django 2.2.7 on 2019-12-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
