# Generated by Django 2.2.7 on 2019-12-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20191224_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='emoji',
            field=models.CharField(default='👽', max_length=1),
            preserve_default=False,
        ),
    ]
