# Generated by Django 2.2.7 on 2019-12-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20191230_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='emoji',
            field=models.CharField(max_length=5),
        ),
    ]
