# Generated by Django 2.2.7 on 2020-01-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20191230_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=25000),
        ),
    ]
