# Generated by Django 2.2.7 on 2020-01-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20200106_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default='null@comradery.io', max_length=254),
            preserve_default=False,
        ),
    ]
