# Generated by Django 2.2.7 on 2020-01-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_auto_20200112_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
