# Generated by Django 2.2.7 on 2020-01-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_auto_20200112_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
