# Generated by Django 2.2.7 on 2020-01-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='custom_stylesheet',
            field=models.URLField(blank=True, null=True),
        ),
    ]
