# Generated by Django 2.2.7 on 2020-01-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0028_auto_20200117_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='login_redirect',
            field=models.URLField(blank=True, null=True),
        ),
    ]
