# Generated by Django 2.2.7 on 2020-01-21 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0030_auto_20200120_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100, unique=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='forum.Community')),
            ],
        ),
    ]
