# Generated by Django 2.2.7 on 2020-01-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0031_communityhost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
