# Generated by Django 2.2.7 on 2020-01-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0033_community_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='write_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
