# Generated by Django 2.2.7 on 2020-01-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0035_person_segment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='track_anonymous',
            field=models.BooleanField(default=True),
        ),
    ]
