# Generated by Django 2.2.7 on 2020-01-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0036_community_track_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
