# Generated by Django 2.2.7 on 2020-01-30 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0037_post_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityhost",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosts",
                to="forum.Community",
            ),
        ),
    ]
