# Generated by Django 2.2.7 on 2020-02-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0039_auto_20200130_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
