# Generated by Django 2.2.7 on 2020-02-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0041_person_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='track_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
