# Generated by Django 2.2.7 on 2020-02-14 20:52

from django.db import migrations, models
import django.db.models.deletion
import forum.utils


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0042_auto_20200203_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=forum.utils.uuid_path),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=forum.utils.uuid_path),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('CL', 'CL'), ('PL', 'PL'), ('PC', 'PC'), ('CC', 'CC')], max_length=5)),
                ('action_takers', models.ManyToManyField(to='forum.Person')),
                ('notified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='forum.Person')),
                ('target_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Comment')),
                ('target_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Post')),
            ],
        ),
    ]
