# Generated by Django 2.2.7 on 2020-02-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0043_auto_20200214_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CL', 'CLa'), ('PL', 'PLa'), ('PC', 'PCa'), ('CC', 'CCa')], max_length=5),
        ),
    ]
