# Generated by Django 2.2.7 on 2020-02-14 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0044_auto_20200214_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action_takers',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Person'),
        ),
        migrations.AddField(
            model_name='notification',
            name='num_other_ats',
            field=models.IntegerField(default=0),
        ),
    ]
