# Generated by Django 2.2.7 on 2020-02-14 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0046_auto_20200214_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Person'),
        ),
    ]
