# Generated by Django 2.2.7 on 2020-02-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0049_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='digest_day_of_week',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='community',
            name='digest_frequency',
            field=models.CharField(choices=[('never', 'never'), ('daily', 'daily'), ('weekly', 'weekly')], default='never', max_length=10),
        ),
    ]
