# Generated by Django 2.2.7 on 2020-02-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0051_auto_20200222_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='sort',
            field=models.IntegerField(default=100),
        ),
    ]
