# Generated by Django 2.2.7 on 2020-02-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0053_auto_20200225_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='notification_frequency',
            field=models.CharField(choices=[('never', 'never'), ('daily', 'daily'), ('hourly', 'hourly')], default='hourly', max_length=10),
        ),
    ]
