# Generated by Django 2.2.7 on 2020-03-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0055_auto_20200302_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='show_welcome',
            field=models.BooleanField(default=True),
        ),
    ]
