# Generated by Django 2.2.7 on 2020-03-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0056_person_show_welcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('room', 'room'), ('direct', 'direct')], default='room', max_length=10),
            preserve_default=False,
        ),
    ]
