# Generated by Django 2.2.7 on 2020-03-08 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0058_auto_20200307_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatRoomMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.IntegerField(default=0)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_metadata', to='forum.ChatRoom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_metadata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
