# Generated by Django 2.2.7 on 2020-03-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0059_userchatroommetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonChatRoomMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.IntegerField(default=0)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons_metadata', to='forum.ChatRoom')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_metadata', to='forum.Person')),
            ],
        ),
        migrations.DeleteModel(
            name='UserChatRoomMetadata',
        ),
    ]
