# Generated by Django 2.2.7 on 2020-03-08 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0060_auto_20200308_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personchatroommetadata',
            name='read_count',
        ),
        migrations.AddField(
            model_name='personchatroommetadata',
            name='last_read',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.Message'),
            preserve_default=False,
        ),
    ]
