# Generated by Django 2.2.7 on 2020-03-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0062_auto_20200312_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=9500),
        ),
    ]
