# Generated by Django 2.2.7 on 2020-03-13 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0063_auto_20200313_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='forum.Community')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='forum.CustomField')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='forum.Person')),
            ],
        ),
    ]
