# Generated by Django 2.2.7 on 2020-03-13 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0064_customfield_customfieldvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActiveDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Person')),
            ],
        ),
    ]
