# Generated by Django 2.2.7 on 2020-03-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0069_auto_20200321_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='welcome_content',
        ),
        migrations.RemoveField(
            model_name='community',
            name='welcome_title',
        ),
    ]
