# Generated by Django 2.2.7 on 2020-03-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0070_auto_20200323_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
