# Generated by Django 2.2.7 on 2020-03-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0072_communityinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='nice_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
