# Generated by Django 2.2.7 on 2020-03-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0073_community_nice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='ff_edit_profile_redirect_enabled',
        ),
        migrations.AddField(
            model_name='community',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
