# Generated by Django 2.2.7 on 2020-03-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0074_auto_20200329_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComraderyBetaInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.CharField(max_length=40)),
            ],
        ),
    ]
