# Generated by Django 2.2.7 on 2020-03-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0075_comraderybetainvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityinvitation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
