# Generated by Django 2.2.7 on 2020-03-29 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0076_communityinvitation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='personchatroommetadata',
            name='last_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='md_emails', to='forum.Message'),
        ),
        migrations.AlterField(
            model_name='personchatroommetadata',
            name='last_read',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Message'),
        ),
    ]
