# Generated by Django 2.2.7 on 2020-04-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0077_auto_20200329_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
