# Generated by Django 2.2.7 on 2020-04-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0078_person_last_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='digest_frequency',
            field=models.CharField(blank=True, choices=[('never', 'never'), ('daily', 'daily'), ('weekly', 'weekly')], max_length=10, null=True),
        ),
    ]
