# Generated by Django 2.2.7 on 2020-04-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0079_person_digest_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='custom_header',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='digest_frequency',
            field=models.CharField(choices=[('immediate', 'immediate'), ('never', 'never'), ('daily', 'daily'), ('weekly', 'weekly')], default='never', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='digest_frequency',
            field=models.CharField(blank=True, choices=[('immediate', 'immediate'), ('never', 'never'), ('daily', 'daily'), ('weekly', 'weekly')], max_length=10, null=True),
        ),
    ]
