# Generated by Django 2.2.7 on 2020-04-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0080_auto_20200418_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='auth',
            field=models.CharField(blank=True, choices=[('slack', 'slack'), ('google', 'google')], max_length=10, null=True),
        ),
    ]
