# Generated by Django 2.2.7 on 2020-04-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0081_person_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='trusted',
        ),
        migrations.AddField(
            model_name='community',
            name='auth_enabled',
            field=models.CharField(blank=True, choices=[('slack', 'slack'), ('google', 'google')], max_length=10, null=True),
        ),
    ]
