# Generated by Django 2.2.7 on 2020-04-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0082_auto_20200420_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='trusted',
            field=models.BooleanField(default=False),
        ),
    ]
