# Generated by Django 2.2.7 on 2020-04-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0083_community_trusted'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='post_admin_only',
            field=models.BooleanField(default=False),
        ),
    ]
