# Generated by Django 2.2.7 on 2020-04-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0084_channel_post_admin_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
