# Generated by Django 2.2.7 on 2020-05-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0086_community_welcome_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='welcome_message',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
