AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_STORAGE_BUCKET_NAME = ""
AWS_S3_CUSTOM_DOMAIN = ""

ALGOLIA_APPLICATION_ID = ''
ALGOLIA_ADMIN_KEY = ''
ALGOLIA_SEARCH_KEY = ''

GOOGLE_AUTH_DEV = ""
GOOGLE_AUTH_PROD = ""

POSTMARK_API_KEY = ""
POSTMARK_SENDER = ""
POSTMARK_INVITATION_TEMPLATE_ID = ""
POSTMARK_NOTIFICATION_TEMPLATE_ID = ""
POSTMARK_PASSWORD_RESET_TEMPLATE_ID = ""

SENDGRID_API_KEY = ""
SENDGRID_NEWSLETTER_TEMPLATE_ID = ""

SEGMENT_WRITE_KEY = ""

PROD_FRONTEND_URL = ""
DEV_FRONTEND_URL = "http://localhost:3000"